export const AGREGAR_FORM = "AGREGAR_FORM";
export const FORM_ERROR= "FORM_ERROR";
export const OCULTAR_MENSAJE = "OCULTAR_MENSAJE";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR= "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

export const OBTENER_CONDADOS = "OBTENER_CONDADOS";